[workspace]
members = [
    "src/backend"
]

[workspace.dependencies]
candid = "0.7.14"
ic-cdk = "0.5.2"
ic-cdk-macros = "0.5.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
hex = "0.4.3"